---
- hosts: all
  become: true

  tasks:

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Include vars of users
    include_vars:
      file: ../users.yml
      name: users

  - name: create a new user
    user:
      name="{{ item.username }}"
      shell="/bin/bash"
      state=present
      groups="wheel"
      append=yes
    with_items: "{{ users.users }}"

  - name: adds key
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ item.pubkey }}"
    with_items: "{{ users.users }}"
