---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
  - name: update apt
    apt:
      update_cache: yes

  # Docker
  - name: ensure repository key is installed
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: ensure docker registry is available
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-engine

  - service: name=docker state=restarted

  - name: install pip
    apt: name=python-pip

  - pip:
      name: docker-py

  - name: Container present
    docker_container:
      name: "testcontainer"
      state: started
      image: alpine
      command: date

  - name: Create nginx-proxy
    docker_container:
      name: "nginx-proxy"
      image: jwilder/nginx-proxy
      state: started
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

  - name: Include vars of users
    include_vars:
      file: users.yml
      name: users

  - name: Create containers for users
    docker_container:
      name: "{{ item.key }}-container"
      env:
        VIRTUAL_HOST: "{{ item.key }}.local"
      state: present
      image: alpine
    with_dict: "{{ users }}"

  - name: Create container to test nginx
    docker_container:
      name: whoami
      image: jwilder/whoami
      expose:
        - "8000"
      env:
        VIRTUAL_HOST: whoami.local
        WEB_PORTS: 8000
      state: started
